// 현재상태 검색은 사건 진행상태·사건 결과·물건 상태를 함께 조회한다.
export const AUCTION_STATUS_OPTIONS = [
  '신건', '유찰', '진행', '매각준비', '매각공고', '매각',
  '매각허가결정', '매각불허가결정', '대금납부', '대금미납', '매각허가취소결정',
  '정지', '취하', '취소', '종결', '배당종결', '기각', '각하', '이송', '미종국',
  '예납필요', '추가예납필요', '추가예납접수중', '미제', '사건보존', '보전처분집행',
  '가보존', '사건종국', '<(재)항고>인용', '<(재)항고>기각', '기타',
];

export const REGION_PROVINCES = [
  '서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종',
  '경기', '강원', '충북', '충남', '전북', '전남', '경북', '경남', '제주',
];

export const PROVINCE_SEARCH_TERMS: Record<string, string> = {
  서울: '서울특별시',
  부산: '부산광역시',
  대구: '대구광역시',
  인천: '인천광역시',
  광주: '광주광역시',
  대전: '대전광역시',
  울산: '울산광역시',
  세종: '세종특별자치시',
  경기: '경기도',
  강원: '강원특별자치도',
  충북: '충청북도',
  충남: '충청남도',
  전북: '전북특별자치도',
  전남: '전라남도',
  경북: '경상북도',
  경남: '경상남도',
  제주: '제주특별자치도',
};

export const SIGUNGU_BY_PROVINCE: Record<string, string[]> = {
  서울: ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
  부산: ['강서구', '금정구', '기장군', '남구', '동구', '동래구', '부산진구', '북구', '사상구', '사하구', '서구', '수영구', '연제구', '영도구', '중구', '해운대구'],
  대구: ['남구', '달서구', '달성군', '동구', '북구', '서구', '수성구', '중구', '군위군'],
  인천: ['강화군', '계양구', '남동구', '동구', '미추홀구', '부평구', '서구', '연수구', '옹진군', '중구'],
  광주: ['광산구', '남구', '동구', '북구', '서구'],
  대전: ['대덕구', '동구', '서구', '유성구', '중구'],
  울산: ['남구', '동구', '북구', '울주군', '중구'],
  세종: ['세종특별자치시'],
  경기: ['가평군', '고양시', '과천시', '광명시', '광주시', '구리시', '군포시', '김포시', '남양주시', '동두천시', '부천시', '성남시', '수원시', '시흥시', '안산시', '안성시', '안양시', '양주시', '양평군', '여주시', '연천군', '오산시', '용인시', '의왕시', '의정부시', '이천시', '파주시', '평택시', '포천시', '하남시', '화성시'],
  강원: ['강릉시', '고성군', '동해시', '삼척시', '속초시', '양구군', '양양군', '영월군', '원주시', '인제군', '정선군', '철원군', '춘천시', '태백시', '평창군', '홍천군', '화천군', '횡성군'],
  충북: ['괴산군', '단양군', '보은군', '영동군', '옥천군', '음성군', '제천시', '증평군', '진천군', '청주시', '충주시'],
  충남: ['계룡시', '공주시', '금산군', '논산시', '당진시', '보령시', '부여군', '서산시', '서천군', '아산시', '예산군', '천안시', '청양군', '태안군', '홍성군'],
  전북: ['고창군', '군산시', '김제시', '남원시', '무주군', '부안군', '순창군', '완주군', '익산시', '임실군', '장수군', '전주시', '정읍시', '진안군'],
  전남: ['강진군', '고흥군', '곡성군', '광양시', '구례군', '나주시', '담양군', '목포시', '무안군', '보성군', '순천시', '신안군', '여수시', '영광군', '영암군', '완도군', '장성군', '장흥군', '진도군', '함평군', '해남군', '화순군'],
  경북: ['경산시', '경주시', '고령군', '구미시', '김천시', '문경시', '봉화군', '상주시', '성주군', '안동시', '영덕군', '영양군', '영주시', '영천시', '예천군', '울릉군', '울진군', '의성군', '청도군', '청송군', '칠곡군', '포항시 남구', '포항시 북구'],
  경남: ['거제시', '거창군', '고성군', '김해시', '남해군', '밀양시', '사천시', '산청군', '양산시', '의령군', '진주시', '창녕군', '창원시', '통영시', '하동군', '함안군', '함양군', '합천군'],
  제주: ['서귀포시', '제주시'],
};

export interface PropertyTypeGroup {
  id: string;
  title: string;
  items: string[];
}

export const PROPERTY_TYPE_GROUPS: PropertyTypeGroup[] = [
  {
    id: 'residential',
    title: '주거용',
    items: ['아파트', '단독주택', '다가구주택', '연립주택', '다세대/빌라'],
  },
  {
    id: 'commercial-industrial',
    title: '상업용',
    items: ['상가', '오피스텔', '근린시설'],
  },
  {
    id: 'land',
    title: '토지',
    items: ['대지', '임야', '전답'],
  },
  {
    id: 'vehicle-heavy-equipment',
    title: '차량 및 중장비',
    items: ['자동차', '중기'],
  },
  {
    id: 'other',
    title: '기타',
    items: ['기타'],
  },
];

export const ALL_PROPERTY_TYPE_ITEMS = PROPERTY_TYPE_GROUPS.flatMap(
  (category) => category.items,
);

export const GOODS_USAGE_VALUES_BY_PROPERTY_TYPE: Record<string, string[]> = {
  아파트: ['아파트'],
  단독주택: ['단독주택', '단독주택,다가구주택'],
  다가구주택: ['다가구주택', '단독주택,다가구주택'],
  연립주택: ['연립주택', '연립주택,다세대,빌라'],
  '다세대/빌라': ['다세대', '빌라', '연립주택,다세대,빌라'],
  상가: ['상가', '상가,오피스텔,근린시설'],
  오피스텔: ['오피스텔', '상가,오피스텔,근린시설'],
  근린시설: ['근린시설', '상가,오피스텔,근린시설'],
  대지: ['대지', '대지,임야,전답'],
  임야: ['임야', '대지,임야,전답'],
  전답: ['전답', '대지,임야,전답'],
  자동차: ['자동차', '자동차,중기'],
  중기: ['중기', '자동차,중기'],
  기타: ['기타'],
};

export const INTERESTED_PARTY_ROLE_OPTIONS: string[] = [
  '신청인',
  '감정인',
  '승계인',
  '이해관계인',
  '채권자',
  '채무자',
  '제3취득자',
  '상대방',
  '근저당권부질권자',
  '수계인',
  '지역권자',
  '소유자',
  '채무자겸소유자',
  '저당권부질권자',
  '상대방겸소유자',
  '신청인겸소유자',
  '상대방겸소유자대리인',
  '신청인겸소유자대리인',
  '최고가매수신고인',
  '차순위매수신고인',
  '임차인',
  '근저당권자',
  '가압류권자',
  '저당권자',
  '전세권자',
  '압류권자',
  '공유자',
  '가등기권자',
  '임금채권자',
  '교부권자',
  '지상권자',
  '가처분권자',
  '배당요구권자',
  '점유자',
  '유치권자',
  '주택임차권자',
  '임차권자',
  '집행관',
  '최고가매수인',
  '차순위매수인',
  '소유자대리인',
  '채무자겸소유자대리인',
  '임차인대리인',
  '임금채권자대리인',
  '배당요구권자대리인',
  '기타',
  '채권자_집행관',
  '채권자_내국인',
  '채권자_외국인',
  '채권자_법인',
  '채권자_검사',
  '대리인',
  '대리인_내국인',
  '대리인_외국인',
  '대리인_법인',
  '채무자_집행관',
  '채무자_내국인',
  '채무자_외국인',
  '채무자_법인',
  '제3채무자',
  '제3채무자_내국인',
  '제3채무자_외국인',
  '제3채무자_법인',
  '채무자의 배우자',
  '채무자의 배우자_내국인',
  '채무자의 배우자_외국인',
  '채무자의 배우자_법인',
  '배당요구자(교부청구등)',
  '배당요구자(교부청구등)_내국인',
  '배당요구자(교부청구등)_외국인',
  '배당요구자(교부청구등)_법인',
  '집행의 제3자',
  '집행의 제3자_내국인',
  '집행의 제3자_외국인',
  '집행의 제3자_법인',
  '매수신고인(경락인)',
  '매수신고인(경락인)_내국인',
  '매수신고인(경락인)_외국인',
  '매수신고인(경락인)_법인',
  '가압류채권자',
  '가압류채권자_내국인',
  '가압류채권자_외국인',
  '가압류채권자_법인',
  '가처분채권자',
  '가처분채권자_내국인',
  '가처분채권자_외국인',
  '가처분채권자_법인',
  '감정촉탁인',
  '감정촉탁인_내국인',
  '감정촉탁인_외국인',
  '감정촉탁인_법인',
  '기타접수자',
  '기타접수자_내국인',
  '기타접수자_외국인',
  '기타접수자_법인',
];

export interface CourtOption {
  courtCode: string;
  courtName: string;
  branchName: string;
}

export const COURT_OPTIONS: CourtOption[] = [
  { courtCode: 'B000210', courtName: '서울', branchName: '서울중앙지방법원' },
  { courtCode: 'B000211', courtName: '서울', branchName: '서울동부지방법원' },
  { courtCode: 'B000215', courtName: '서울', branchName: '서울서부지방법원' },
  { courtCode: 'B000212', courtName: '서울', branchName: '서울남부지방법원' },
  { courtCode: 'B000213', courtName: '서울', branchName: '서울북부지방법원' },
  { courtCode: 'B000214', courtName: '의정부', branchName: '의정부지방법원' },
  { courtCode: 'B214807', courtName: '의정부', branchName: '고양지원' },
  { courtCode: 'B214804', courtName: '의정부', branchName: '남양주지원' },
  { courtCode: 'B000240', courtName: '인천', branchName: '인천지방법원' },
  { courtCode: 'B000241', courtName: '인천', branchName: '부천지원' },
  { courtCode: 'B000250', courtName: '수원', branchName: '수원지방법원' },
  { courtCode: 'B000251', courtName: '수원', branchName: '성남지원' },
  { courtCode: 'B000252', courtName: '수원', branchName: '여주지원' },
  { courtCode: 'B000253', courtName: '수원', branchName: '평택지원' },
  { courtCode: 'B250826', courtName: '수원', branchName: '안산지원' },
  { courtCode: 'B000254', courtName: '수원', branchName: '안양지원' },
  { courtCode: 'B000260', courtName: '춘천', branchName: '춘천지방법원' },
  { courtCode: 'B000261', courtName: '춘천', branchName: '강릉지원' },
  { courtCode: 'B000262', courtName: '춘천', branchName: '원주지원' },
  { courtCode: 'B000263', courtName: '춘천', branchName: '속초지원' },
  { courtCode: 'B000264', courtName: '춘천', branchName: '영월지원' },
  { courtCode: 'B000270', courtName: '청주', branchName: '청주지방법원' },
  { courtCode: 'B000271', courtName: '청주', branchName: '충주지원' },
  { courtCode: 'B000272', courtName: '청주', branchName: '제천지원' },
  { courtCode: 'B000273', courtName: '청주', branchName: '영동지원' },
  { courtCode: 'B000280', courtName: '대전', branchName: '대전지방법원' },
  { courtCode: 'B000281', courtName: '대전', branchName: '홍성지원' },
  { courtCode: 'B000282', courtName: '대전', branchName: '논산지원' },
  { courtCode: 'B000283', courtName: '대전', branchName: '천안지원' },
  { courtCode: 'B000284', courtName: '대전', branchName: '공주지원' },
  { courtCode: 'B000285', courtName: '대전', branchName: '서산지원' },
  { courtCode: 'B000310', courtName: '대구', branchName: '대구지방법원' },
  { courtCode: 'B000311', courtName: '대구', branchName: '안동지원' },
  { courtCode: 'B000312', courtName: '대구', branchName: '경주지원' },
  { courtCode: 'B000313', courtName: '대구', branchName: '김천지원' },
  { courtCode: 'B000314', courtName: '대구', branchName: '상주지원' },
  { courtCode: 'B000315', courtName: '대구', branchName: '의성지원' },
  { courtCode: 'B000316', courtName: '대구', branchName: '영덕지원' },
  { courtCode: 'B000317', courtName: '대구', branchName: '포항지원' },
  { courtCode: 'B000320', courtName: '대구', branchName: '대구서부지원' },
  { courtCode: 'B000410', courtName: '부산', branchName: '부산지방법원' },
  { courtCode: 'B000412', courtName: '부산', branchName: '부산동부지원' },
  { courtCode: 'B000414', courtName: '부산', branchName: '부산서부지원' },
  { courtCode: 'B000411', courtName: '울산', branchName: '울산지방법원' },
  { courtCode: 'B000420', courtName: '창원', branchName: '창원지방법원' },
  { courtCode: 'B000431', courtName: '창원', branchName: '마산지원' },
  { courtCode: 'B000421', courtName: '창원', branchName: '진주지원' },
  { courtCode: 'B000422', courtName: '창원', branchName: '통영지원' },
  { courtCode: 'B000423', courtName: '창원', branchName: '밀양지원' },
  { courtCode: 'B000424', courtName: '창원', branchName: '거창지원' },
  { courtCode: 'B000510', courtName: '광주', branchName: '광주지방법원' },
  { courtCode: 'B000511', courtName: '광주', branchName: '목포지원' },
  { courtCode: 'B000512', courtName: '광주', branchName: '장흥지원' },
  { courtCode: 'B000513', courtName: '광주', branchName: '순천지원' },
  { courtCode: 'B000514', courtName: '광주', branchName: '해남지원' },
  { courtCode: 'B000520', courtName: '전주', branchName: '전주지방법원' },
  { courtCode: 'B000521', courtName: '전주', branchName: '군산지원' },
  { courtCode: 'B000522', courtName: '전주', branchName: '정읍지원' },
  { courtCode: 'B000523', courtName: '전주', branchName: '남원지원' },
  { courtCode: 'B000530', courtName: '제주', branchName: '제주지방법원' },
];
